In [1]:
import tensorflow as tf

In [3]:
tf.__version__

'2.1.0'

In [4]:
import pandas as pd

In [5]:
DATA_FILE = 'datasets/cars_sample.csv.zip'

In [6]:
df = pd.read_csv(DATA_FILE)

In [7]:
_ = df.pop('model')

In [8]:
y = df.pop('price')

In [9]:
categ_columns = ['region', 'year', 'manufacturer', 'condition', 'cylinders',
       'fuel', 'transmission', 'drive', 'size', 'type',
       'paint_color']

df_sparse = pd.get_dummies(df, columns=categ_columns)

In [10]:
df_sparse.shape

(90496, 593)

In [11]:
X = df_sparse.values

In [12]:
X_train = X[:-100]
y_train = y[:-100]
X_test = X[-100:]
y_test = y[-100:]

In [13]:
tf_x_train = tf.constant(X_train)
tf_y_train = tf.constant(y_train)
tf_x_test = tf.constant(X_test)

In [14]:
tf_x_train.device

'/job:localhost/replica:0/task:0/device:CPU:0'

In [15]:
tf_x_train

<tf.Tensor: shape=(90396, 593), dtype=float64, numpy=
array([[5.40000e+04, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [6.28000e+04, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [3.29890e+04, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       ...,
       [3.52781e+05, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 0.00000e+00],
       [4.79000e+04, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00],
       [8.29540e+04, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 0.00000e+00]])>

In [16]:
tf_a = tf.linalg.inv(tf.matmul(tf_x_train, tf_x_train, transpose_a=True))

In [17]:
tf_a.device

'/job:localhost/replica:0/task:0/device:GPU:0'

In [19]:
tf_theta = tf.matmul(tf.matmul(tf_a, tf_x_train, transpose_b=True), tf_y_train)

InvalidArgumentError: cannot compute MatMul as input #1(zero-based) was expected to be a double tensor but is a int32 tensor [Op:MatMul] name: MatMul/

In [20]:
tf_y_train

<tf.Tensor: shape=(90396,), dtype=int32, numpy=array([ 9000,  8500, 24930, ...,     0, 17500,     0])>

In [24]:
tf_y_train = tf.constant(y_train, dtype='float64')

In [25]:
tf_theta = tf.matmul(tf.matmul(tf_a, tf_x_train, transpose_b=True), tf_y_train)

InvalidArgumentError: In[1] is not a matrix. Instead it has shape [90396] [Op:MatMul] name: MatMul/

In [29]:
tf_y_train = tf.reshape(tf_y_train, shape=[-1, 1])

In [30]:
tf_y_train

<tf.Tensor: shape=(90396, 1), dtype=float64, numpy=
array([[ 9000.],
       [ 8500.],
       [24930.],
       ...,
       [    0.],
       [17500.],
       [    0.]])>

In [31]:
tf_theta = tf.matmul(tf.matmul(tf_a, tf_x_train, transpose_b=True), tf_y_train)

In [34]:
tf_theta.shape

TensorShape([593, 1])

In [36]:
print(type(tf_theta.numpy()))
tf_theta.shape

<class 'numpy.ndarray'>


TensorShape([593, 1])

In [ ]:
# finalize experiment with tf_X_test.tf_theta VS y_test